services:
  - type: web
    name: connect-your-phone
    env: python
    buildCommand: pip install -r signaling_server/requirements.txt
    startCommand: python signaling_server/server.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
